if(window.location!==window.top.location){top.location.href='https://strobe.cool/';}
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');ga('create','UA-56095-19','auto');ga('send','pageview');window.onerror=function(message,file,line){if(message){ga('send','event','Error',message,file&&line?('['+ file+':'+ line+']'):'',true);}
return false;};window.requestAnimationFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){setTimeout(callback,1000/60);};window.AudioContext=window.AudioContext||window.webkitAudioContext;document.exitFullscreen=document.exitFullscreen||document.webkitExitFullscreen||document.webkitCancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen;try{var get=document.querySelector.bind(document),getAll=document.querySelectorAll.bind(document),on=document.addEventListener.bind(document);Element.prototype.get=Element.prototype.querySelector;Element.prototype.on=Element.prototype.addEventListener;Element.prototype.show=function(){this.classList.remove('hidden');};Element.prototype.hide=function(){this.classList.add('hidden');};Element.prototype.fadeIn=function(){this.show();this.classList.add('fade');this.classList.remove('left');this.classList.remove('right');};Element.prototype.fadeOut=function(){this.classList.remove('fade');};Element.prototype.left=function(){this.classList.add('left');};Element.prototype.right=function(){this.classList.add('right');};}catch(e){}
Date.now=Date.now||function(){return new Date().getTime();};if(!('performance'in window)){window.performance={};}
if(!('now'in window.performance)){var nowOffset=Date.now();if(performance.timing&&performance.timing.navigationStart){nowOffset=performance.timing.navigationStart;}
window.performance.now=function(){return Date.now()- nowOffset;};}
(function(){var ui={},fps={},canvas,gl,audio={},audioContext,now,pixelRatio=window.devicePixelRatio||1,isAnimating=false,socialShare='none',repeatCount=0,DURATION=30,SPEED=120,timer,timerID,strobeVertex='attribute vec3 p;void main(void){gl_Position=vec4(p,1.0);}',strobeFragment='precision highp float;uniform vec2 resolution;uniform float time;uniform float scale;void main(void){vec2 p=abs(gl_FragCoord.xy-resolution/2.0);float f=time*scale;float n=(p.x+p.y)/2.0+mix(f,-f,step(length(resolution)/5.5,length(p)));gl_FragColor=vec4(vec3(sin(n/5.0/scale)*8.0),1.0);}';function createShader(src,type){var shader=gl.createShader(type);gl.shaderSource(shader,src);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){return null;}
return shader;}
function initGL(){if(!window.WebGLRenderingContext){return false;}
try{var attribs={alpha:false,premultipliedAlpha:false};gl=canvas.getContext('webgl',attribs)||canvas.getContext('experimental-webgl',attribs);}catch(e){gl=null;}
if(!gl){return false;}
gl.uniforms={resolution:{},time:0,scale:1,fade:1};gl.buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,gl.buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1.0,-1.0,1.0,-1.0,-1.0,1.0,1.0,-1.0,1.0,1.0,-1.0,1.0]),gl.STATIC_DRAW);var program=gl.createProgram(),vs=createShader(strobeVertex,gl.VERTEX_SHADER),fs=createShader(strobeFragment,gl.FRAGMENT_SHADER);if(!vs||!fs){return false;}
gl.attachShader(program,vs);gl.attachShader(program,fs);gl.deleteShader(vs);gl.deleteShader(fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS)){return false;}
gl.program=program;return!!gl;}
function requestFullscreen(){var el=document.body;try{if(el.requestFullscreen){el.requestFullscreen();}
else if(el.webkitRequestFullscreen){el.webkitRequestFullscreen();}
else if(el.webkitRequestFullScreen){el.webkitRequestFullScreen();}
else if(el.mozRequestFullScreen){el.mozRequestFullScreen();}}catch(e){}
ga('send','event','Fullscreen','enter');}
function exitFullscreen(){if(document.fullscreen||document.webkitIsFullScreen||document.mozFullScreen){document.exitFullscreen();ga('send','event','Fullscreen','exit');}}
function loadAudio(name){var xhr=new XMLHttpRequest();xhr.open('GET','/assets/audio/'+ name+'.mp3',true);xhr.responseType='arraybuffer';xhr.onload=function(){audioContext.decodeAudioData(xhr.response,function(buffer){audio[name]=buffer;},function(){});};xhr.send();}
function playAudio(name){if(!audio[name]){return;}
var source=audioContext.createBufferSource();source.buffer=audio[name];source.connect(audioContext.destination);if(source.start){source.start(0);}else{source.noteOn(0);}}
function resizeCanvas(){canvas.width=innerWidth*pixelRatio;canvas.height=innerHeight*pixelRatio;gl.uniforms.resolution.width=canvas.width;gl.uniforms.resolution.height=canvas.height;gl.uniforms.scale=Math.sqrt(innerWidth*innerHeight)>880?1:0.6;gl.viewport(0,0,canvas.width,canvas.height);}
function updateFPS(){fps.rate=1000/(performance.now()- fps.now);fps.now=performance.now();if(fps.drop<fps.dropMax&&fps.rate<fps.rateMin){fps.drop++;if(fps.drop>=fps.dropMax){if(window.devicePixelRatio>1){pixelRatio=1;}else{pixelRatio=0.5;}
resizeCanvas();}}}
function drawStrobe(){if(!isAnimating||!gl.program){return;}
requestAnimationFrame(drawStrobe);updateFPS();gl.uniforms.time=(performance.now()- now)/ 1000 * SPEED;
if(gl.uniforms.fade>0){gl.uniforms.fade-=0.05;}else{gl.uniforms.fade=0;}
gl.useProgram(gl.program);gl.uniform2f(gl.getUniformLocation(gl.program,'resolution'),gl.uniforms.resolution.width,gl.uniforms.resolution.height);gl.uniform1f(gl.getUniformLocation(gl.program,'time'),gl.uniforms.time);gl.uniform1f(gl.getUniformLocation(gl.program,'scale'),gl.uniforms.scale*pixelRatio);gl.bindBuffer(gl.ARRAY_BUFFER,gl.buffer);gl.vertexAttribPointer(0,2,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(0);gl.drawArrays(gl.TRIANGLES,0,6);gl.disableVertexAttribArray(0);}
function updateTimer(){if(timer>0){ui.timer.innerText=timer;timer--;if(timer<3){playAudio('high');}else if(timer<9){playAudio('low');}
timerID=setTimeout(updateTimer,1000);}else{playAudio('high');showOutro();}}
function sleep(duration,callback){return setTimeout(callback,duration);}
function showIntro(){ui.section.alt.hide();ui.section.intro.show();ui.introButton.hide();ui.introText[0].left();ui.introText[1].right();sleep(200,function(){ui.introTitle.fadeIn();sleep(1000,function(){ui.introText[0].fadeIn();sleep(1500,function(){document.title=document.title.split(' - ')[0]||document.title;ui.introText[1].fadeIn();ui.introButton.fadeIn();});});});}
function hideIntro(){ui.introText[0].fadeOut();ui.introText[1].fadeOut();ui.introTitle.fadeOut();ui.introButton.fadeOut();playAudio('low');sleep(400,showInstructions);}
function showInstructions(){ui.section.intro.hide();ui.section.outro.hide();ui.section.instructions.show();ui.instructionsText[0].left();ui.instructionsText[1].right();ui.instructionsButton.hide();sleep(50,function(){ui.instructionsText[0].fadeIn();sleep(200,function(){ui.instructionsText[1].fadeIn();sleep(300,function(){ui.instructionsButton.fadeIn();ui.instructionsWarning.fadeIn();});});});}
function hideInstructions(){ui.instructionsText[0].fadeOut();ui.instructionsText[1].fadeOut();ui.instructionsButton.fadeOut();ui.instructionsWarning.fadeOut();canvas.show();playAudio('low');sleep(400,showStrobe);}
function showStrobe(){if(innerWidth/screen.width<0.4){requestFullscreen();}
sleep(50,function(){isAnimating=true;ui.section.instructions.hide();timer=DURATION;updateTimer();ui.timer.show();now=performance.now();drawStrobe();canvas.fadeIn();});}
function showOutro(event){if(isAnimating&&(timer<DURATION- 2||event)){isAnimating=false;exitFullscreen();ga('send','event','Duration',DURATION- timer);canvas.hide();canvas.fadeOut();clearTimeout(timerID);ui.timer.innerText='';ui.timer.hide();ui.section.outro.show();ui.outroTitle.fadeIn();ui.outroTitle.classList.add('down');ui.repeatButton.hide();ui.shareButton.hide();if(ui.appButton){ui.appButton.hide();}
sleep(timer>DURATION/2?500:2000,function(){ui.outroTitle.classList.remove('down');ui.outroText[0].left();if(ui.outroText[1]){ui.outroText[1].right();}
sleep(500,function(){ui.outroText[0].fadeIn();if(ui.outroText[1]){ui.outroText[1].fadeIn();}
ui.repeatButton.fadeIn();ui.shareButton.fadeIn();if(ui.appButton){ui.appButton.fadeIn();}});});}}
function hideOutro(){repeatCount++;ga('send','event','Repeat',repeatCount);ui.outroTitle.fadeOut();ui.outroText[0].fadeOut();ui.repeatButton.fadeOut();ui.shareButton.fadeOut();if(ui.appButton){ui.appButton.fadeOut();}
if(ui.outroText[1]){ui.outroText[1].fadeOut();}
playAudio('low');sleep(400,showInstructions);}
function openWindow(url){var width=560,height=290,left=screenX+(innerWidth- width)/ 2,
top=screenY+(innerHeight- height)/ 2;
window.open(url,'strobe-twitter','resizable=yes,toolbar=no,scrollbars=yes,status=no,width='+ width+',height='+ height+',left='+ left+',top='+ top);}
function checkFacebookLoginStatus(){window.fbAsyncInit=function(){FB.init({appId:'702869293196589',version:'v2.7'});FB.getLoginStatus(function(response){socialShare=(response.status==='unknown')?'none':'Facebook';ga('send','event','Social',socialShare);});};(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return;}
js=d.createElement(s);js.id=id;js.src='https://connect.facebook.net/en_US/sdk.js';fjs.parentNode.insertBefore(js,fjs);}(document,'script','facebook-jssdk'));}
function checkTwitterLoginStatus(){var img=document.createElement('img');img.onload=function(){socialShare='Twitter';ga('send','event','Social',socialShare);};img.onerror=checkFacebookLoginStatus;img.src='https://twitter.com/login?redirect_after_login=%2Ffavicon.ico';}
function initStrobe(){canvas=get('.strobe');canvas.oncontextmenu=function(event){event.preventDefault();};ui={section:{alt:get('.alt'),intro:get('.intro'),instructions:get('.instructions'),outro:get('.outro')},introTitle:get('.intro h1'),introText:getAll('.intro > p'),introButton:get('.intro .button'),instructionsButton:get('.instructions .button'),instructionsText:getAll('.instructions > p'),instructionsWarning:get('.instructions .warning'),outroTitle:get('.outro h2'),outroText:getAll('.outro > p'),repeatButton:get('.outro .button.repeat'),shareButton:get('.outro .button.share'),appButton:get('.outro .button.app'),timer:get('.timer')};if(initGL()){ga('send','event','WebGL','true');fps={rate:0,now:0,drop:0,dropMax:10,rateMin:40};resizeCanvas();window.onresize=resizeCanvas;ui.introButton.onclick=hideIntro;ui.instructionsButton.onclick=hideInstructions;window.onblur=canvas.onmouseleave=showOutro;canvas.onmousedown=function(){showOutro();};ui.repeatButton.onclick=hideOutro;ui.shareButton.onclick=openShareWindow;if(ui.appButton){ui.appButton.onclick=function(){ga('send','event','App','desktop');};}
on('visibilitychange',function(){if(document.hidden){showOutro();}});if(window.AudioContext){audioContext=new AudioContext();loadAudio('low');loadAudio('high');}
checkTwitterLoginStatus();showIntro();}else{ga('send','event','WebGL','false');try{ui.section.alt.show();sleep(250,function(){get('.alt.webgl h1').fadeIn();});}catch(e){}}}
on('DOMContentLoaded',initStrobe);})();